### ISSUE TITLE
Error on running `yarn dev`

### ISSUE THREAD

**Issue by HeroicHitesh** [coderplex/learnplex-backend#32]
on running `yarn dev` I am getting this error
```
yarn run v1.22.4
$ ts-node-dev --ignore-watch node_modules --respawn src/index.ts
Ignore watch: [ 'node_modules' ]
Using ts-node version 8.10.1, typescript version 3.9.3
(node:69565) UnhandledPromiseRejectionWarning: error: database "coderplex" does not exist
    at Parser.parseErrorMessage (/Users/apple/Developer/GitHub/coderplex/learnplex-backend/node_modules/pg-protocol/src/parser.ts:325:11)
    at Parser.handlePacket (/Users/apple/Developer/GitHub/coderplex/learnplex-backend/node_modules/pg-protocol/src/parser.ts:154:21)
    at Parser.parse (/Users/apple/Developer/GitHub/coderplex/learnplex-backend/node_modules/pg-protocol/src/parser.ts:106:30)
    at Socket.<anonymous> (/Users/apple/Developer/GitHub/coderplex/learnplex-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:69565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

@pbteja1998  How to resolve this?

**Comment by HeroicHitesh** [comment]
Some references to study for resolving this issue
https://stackoverflow.com/questions/40500490/what-is-an-unhandled-promise-rejection
https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html#deprecations_dep0018_unhandled_promise_rejections
https://medium.com/@dtinth/making-unhandled-promise-rejections-crash-the-node-js-process-ffc27cfcc9dd
https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html

I didn't understand much but after reading through these references I guess this issue is not causing anything to break now. And hence I was able to run PgAdmin successfully.
